// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20260407145042_order")]
    partial class order
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("backend.Models.Admin.BangLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<double>("PhuCapAnTrua")
                        .HasColumnType("float");

                    b.Property<double>("PhuCapChuyenCan")
                        .HasColumnType("float");

                    b.Property<double>("PhuCapXangXe")
                        .HasColumnType("float");

                    b.Property<int>("TaiKhoanNoiBoId")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<double>("TienPhatDiMuon")
                        .HasColumnType("float");

                    b.Property<double>("TongGioLam")
                        .HasColumnType("float");

                    b.Property<double>("TongNgayLam")
                        .HasColumnType("float");

                    b.Property<double>("TongPhuCap")
                        .HasColumnType("float");

                    b.Property<double>("TongTienNhan")
                        .HasColumnType("float");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanNoiBoId");

                    b.ToTable("BangLuong");
                });

            modelBuilder.Entity("backend.Models.Admin.BienLai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CuaHangId")
                        .HasColumnType("int");

                    b.Property<int?>("DoiTacId")
                        .HasColumnType("int");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("KhoXuatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CuaHangId");

                    b.HasIndex("DoiTacId");

                    b.ToTable("BienLai");
                });

            modelBuilder.Entity("backend.Models.Admin.CaLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("TenCa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CaLamViec");
                });

            modelBuilder.Entity("backend.Models.Admin.CauHinhLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LoaiLuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("MucLuong")
                        .HasColumnType("float");

                    b.Property<double>("PhuCapAnTrua")
                        .HasColumnType("float");

                    b.Property<double>("PhuCapChuyenCan")
                        .HasColumnType("float");

                    b.Property<double>("PhuCapXangXe")
                        .HasColumnType("float");

                    b.Property<int>("TaiKhoanNoiBoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanNoiBoId");

                    b.ToTable("CauHinhLuong");
                });

            modelBuilder.Entity("backend.Models.Admin.ChamCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CaLamViecId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GioRa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GioVao")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaiKhanNoiBoId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("backend.Models.Admin.ChiTietBienLai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BienLaiId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("NguyenLieuId")
                        .HasColumnType("int");

                    b.Property<float>("Soluong")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BienLaiId");

                    b.HasIndex("NguyenLieuId");

                    b.ToTable("ChiTietBienLai");
                });

            modelBuilder.Entity("backend.Models.Admin.ChiTietKiemKe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("ChenhLech")
                        .HasColumnType("real");

                    b.Property<int>("KiemKeId")
                        .HasColumnType("int");

                    b.Property<int>("NguyenLieuId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TonHeThong")
                        .HasColumnType("real");

                    b.Property<float>("TonThucTe")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("KiemKeId");

                    b.HasIndex("NguyenLieuId");

                    b.ToTable("ChiTietKiemKe");
                });

            modelBuilder.Entity("backend.Models.Admin.ChucVu", b =>
                {
                    b.Property<int>("ChucVuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChucVuId"), 1L, 1);

                    b.Property<string>("ChucVuDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ChucVuName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ChucVuId");

                    b.ToTable("ChucVu");

                    b.HasData(
                        new
                        {
                            ChucVuId = 1,
                            ChucVuDescription = "Người quản lý tất cả. tạo tài khoản các phòng ban",
                            ChucVuName = "Admin"
                        },
                        new
                        {
                            ChucVuId = 2,
                            ChucVuDescription = "Người tính lương, duyệt thu chi từ kho và QL khu vực",
                            ChucVuName = "Accountant"
                        },
                        new
                        {
                            ChucVuId = 3,
                            ChucVuDescription = "Người tiếp nhận đặt hàng từ cửa hàng, đặt hàng với bên thứ 3, phiếu nhập và xuất kho từ CH và bên thứ 3",
                            ChucVuName = "Production"
                        },
                        new
                        {
                            ChucVuId = 4,
                            ChucVuDescription = "Người quản lý các CH do GD phân, làm phiếu đề xuất khi CH cần, ql công ca NV cửa hàng",
                            ChucVuName = "AreaManager"
                        },
                        new
                        {
                            ChucVuId = 5,
                            ChucVuDescription = "Người đặt thực phẩm với kho, tạo các phiếu điều chuyển giữ các cửa hàng, xem báo cáo doanh thu và đặt thực phẩm",
                            ChucVuName = "StoreManager"
                        },
                        new
                        {
                            ChucVuId = 6,
                            ChucVuDescription = "xem được công ca, phiếu lương",
                            ChucVuName = "Sales"
                        },
                        new
                        {
                            ChucVuId = 7,
                            ChucVuDescription = "Đặt hàng qua web, tích điểm",
                            ChucVuName = "Customer"
                        },
                        new
                        {
                            ChucVuId = 8,
                            ChucVuDescription = "máy ở CH để nhân viên order trực tiếp",
                            ChucVuName = "POS"
                        },
                        new
                        {
                            ChucVuId = 9,
                            ChucVuDescription = "Phân chức vụ các phòng ban ",
                            ChucVuName = "HR"
                        });
                });

            modelBuilder.Entity("backend.Models.Admin.CuaHang", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopId"), 1L, 1);

                    b.Property<int>("BanKinhChoPhep")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("ShopAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShopId");

                    b.ToTable("cuaHangs");
                });

            modelBuilder.Entity("backend.Models.Admin.DoiTac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DoiTac");
                });

            modelBuilder.Entity("backend.Models.Admin.KiemKe", b =>
                {
                    b.Property<int>("KiemKeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KiemKeId"), 1L, 1);

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("KiemKeId");

                    b.HasIndex("ShopId");

                    b.ToTable("KiemKe");
                });

            modelBuilder.Entity("backend.Models.Admin.LichLamViec", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CaLamViecId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLamViec")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("TaiKhoanNoiBoId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("LichLamViec");
                });

            modelBuilder.Entity("backend.Models.Admin.MaGiamGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiMa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MaxValue")
                        .HasColumnType("real");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MaGiamGia");
                });

            modelBuilder.Entity("backend.Models.Admin.NguyenLieu", b =>
                {
                    b.Property<int>("NguyenLieuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguyenLieuId"), 1L, 1);

                    b.Property<int?>("DoiTacId")
                        .HasColumnType("int");

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HanSuDung")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgaySanXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguyenLieuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TheLoaiId")
                        .HasColumnType("int");

                    b.HasKey("NguyenLieuId");

                    b.HasIndex("DoiTacId");

                    b.HasIndex("TheLoaiId");

                    b.ToTable("NguyenLieu");
                });

            modelBuilder.Entity("backend.Models.Admin.SanPham", b =>
                {
                    b.Property<int>("SanPhamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SanPhamId"), 1L, 1);

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguyenLieuId")
                        .HasColumnType("int");

                    b.Property<string>("SanPhamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TheLoaiId")
                        .HasColumnType("int");

                    b.HasKey("SanPhamId");

                    b.HasIndex("NguyenLieuId");

                    b.HasIndex("TheLoaiId");

                    b.ToTable("sanPhams");
                });

            modelBuilder.Entity("backend.Models.Admin.TaiKhoanNoiBo", b =>
                {
                    b.Property<int>("TaiKhoanNoiBoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanNoiBoId"), 1L, 1);

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChucVuId")
                        .HasColumnType("int");

                    b.Property<int?>("CuaHangId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaiKhoanNoiBoId");

                    b.HasIndex("ChucVuId");

                    b.HasIndex("CuaHangId");

                    b.ToTable("TaiKhoanNoiBo");

                    b.HasData(
                        new
                        {
                            TaiKhoanNoiBoId = 1,
                            Avatar = "",
                            ChucVuId = 1,
                            Email = "cn908820@gmail.com",
                            GioiTinh = false,
                            IsActive = true,
                            MatKhau = "$2a$11$v1ky6FrsfE5FNWLl6stSlurK9VYN0b09.0FMsQNvNli/c41yUrLF6",
                            NgaySinh = new DateTime(2004, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayThamGia = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Sdt = "0909999999",
                            TenNhanVien = "Nguyễn Minh Chiến",
                            TenTaiKhoan = "nmchien@giamdoc.food.com"
                        });
                });

            modelBuilder.Entity("backend.Models.Admin.TheLoai", b =>
                {
                    b.Property<int>("TheLoaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TheLoaiId"), 1L, 1);

                    b.Property<string>("TheLoaiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TheLoaiId");

                    b.ToTable("theLoais");

                    b.HasData(
                        new
                        {
                            TheLoaiId = 1,
                            TheLoaiName = "Bán thành phẩm"
                        },
                        new
                        {
                            TheLoaiId = 2,
                            TheLoaiName = "Thành phẩm"
                        },
                        new
                        {
                            TheLoaiId = 3,
                            TheLoaiName = "Rau củ "
                        },
                        new
                        {
                            TheLoaiId = 4,
                            TheLoaiName = "Công cụ dụng cụ "
                        },
                        new
                        {
                            TheLoaiId = 5,
                            TheLoaiName = "Nguyên vật liệu "
                        },
                        new
                        {
                            TheLoaiId = 6,
                            TheLoaiName = "Đồ chơi "
                        },
                        new
                        {
                            TheLoaiId = 7,
                            TheLoaiName = "Thương mại "
                        },
                        new
                        {
                            TheLoaiId = 8,
                            TheLoaiName = "Topping"
                        },
                        new
                        {
                            TheLoaiId = 9,
                            TheLoaiName = "Sữa hạt"
                        });
                });

            modelBuilder.Entity("backend.Models.Admin.TonKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("NguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<float>("SoLuong")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("NguyenLieuId");

                    b.HasIndex("ShopId");

                    b.ToTable("tonKhos");
                });

            modelBuilder.Entity("backend.Models.Client.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("backend.Models.Client.CartDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsKhongNau")
                        .HasColumnType("bit");

                    b.Property<int?>("RauCuNguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("RauCuNguyenLieuId");

                    b.ToTable("CartDetail");
                });

            modelBuilder.Entity("backend.Models.Client.CartDetailTopping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartDetailId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("ToppingSanPhamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartDetailId");

                    b.HasIndex("ToppingSanPhamId");

                    b.ToTable("CartDetailTopping");
                });

            modelBuilder.Entity("backend.Models.Client.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DiaChiGiaoHang")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("DiemCongThem")
                        .HasColumnType("float");

                    b.Property<double>("DiemSuDung")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsThanhToan")
                        .HasColumnType("bit");

                    b.Property<int?>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiDonHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaDonHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<double>("PhiGiaoHang")
                        .HasColumnType("float");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SdtNguoiNhan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int?>("TaiKhoanNoiBoId")
                        .HasColumnType("int");

                    b.Property<string>("TenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.Property<double>("TienGiamGia")
                        .HasColumnType("float");

                    b.Property<double>("TongTienHang")
                        .HasColumnType("float");

                    b.Property<string>("TrangThaiDonHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("ShopId");

                    b.HasIndex("TaiKhoanNoiBoId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("backend.Models.Client.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsKhongNau")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("RauCuNguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double>("ThanhTien")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("RauCuNguyenLieuId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("backend.Models.Client.OrderDetailTopping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("GiaTopping")
                        .HasColumnType("float");

                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("ToppingSanPhamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailId");

                    b.HasIndex("ToppingSanPhamId");

                    b.ToTable("OrderDetailTopping");
                });

            modelBuilder.Entity("backend.Models.Client.TaiKhoanKhachHang", b =>
                {
                    b.Property<int>("KhachHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhachHangId"), 1L, 1);

                    b.Property<int>("ChucVuId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("TichDiem")
                        .HasColumnType("float");

                    b.HasKey("KhachHangId");

                    b.HasIndex("ChucVuId");

                    b.ToTable("taiKhoanKhachHang");
                });

            modelBuilder.Entity("backend.Models.Admin.BangLuong", b =>
                {
                    b.HasOne("backend.Models.Admin.TaiKhoanNoiBo", "TaiKhoanNoiBo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanNoiBoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoanNoiBo");
                });

            modelBuilder.Entity("backend.Models.Admin.BienLai", b =>
                {
                    b.HasOne("backend.Models.Admin.CuaHang", "CuaHang")
                        .WithMany()
                        .HasForeignKey("CuaHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Admin.DoiTac", "DoiTac")
                        .WithMany()
                        .HasForeignKey("DoiTacId");

                    b.Navigation("CuaHang");

                    b.Navigation("DoiTac");
                });

            modelBuilder.Entity("backend.Models.Admin.CauHinhLuong", b =>
                {
                    b.HasOne("backend.Models.Admin.TaiKhoanNoiBo", "TaiKhoanNoiBo")
                        .WithMany()
                        .HasForeignKey("TaiKhoanNoiBoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoanNoiBo");
                });

            modelBuilder.Entity("backend.Models.Admin.ChiTietBienLai", b =>
                {
                    b.HasOne("backend.Models.Admin.BienLai", "BienLai")
                        .WithMany()
                        .HasForeignKey("BienLaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Admin.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienLai");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("backend.Models.Admin.ChiTietKiemKe", b =>
                {
                    b.HasOne("backend.Models.Admin.KiemKe", "KiemKe")
                        .WithMany()
                        .HasForeignKey("KiemKeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Admin.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KiemKe");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("backend.Models.Admin.KiemKe", b =>
                {
                    b.HasOne("backend.Models.Admin.CuaHang", "CuaHang")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuaHang");
                });

            modelBuilder.Entity("backend.Models.Admin.NguyenLieu", b =>
                {
                    b.HasOne("backend.Models.Admin.DoiTac", "DoiTac")
                        .WithMany()
                        .HasForeignKey("DoiTacId");

                    b.HasOne("backend.Models.Admin.TheLoai", "TheLoai")
                        .WithMany()
                        .HasForeignKey("TheLoaiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoiTac");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("backend.Models.Admin.SanPham", b =>
                {
                    b.HasOne("backend.Models.Admin.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Admin.TheLoai", "TheLoai")
                        .WithMany("sanPhams")
                        .HasForeignKey("TheLoaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("backend.Models.Admin.TaiKhoanNoiBo", b =>
                {
                    b.HasOne("backend.Models.Admin.ChucVu", "ChucVu")
                        .WithMany("taiKhoanNoiBos")
                        .HasForeignKey("ChucVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Admin.CuaHang", "CuaHang")
                        .WithMany()
                        .HasForeignKey("CuaHangId");

                    b.Navigation("ChucVu");

                    b.Navigation("CuaHang");
                });

            modelBuilder.Entity("backend.Models.Admin.TonKho", b =>
                {
                    b.HasOne("backend.Models.Admin.NguyenLieu", "NguyenLieu")
                        .WithMany()
                        .HasForeignKey("NguyenLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Admin.CuaHang", "CuaHang")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuaHang");

                    b.Navigation("NguyenLieu");
                });

            modelBuilder.Entity("backend.Models.Client.Cart", b =>
                {
                    b.HasOne("backend.Models.Client.TaiKhoanKhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("backend.Models.Client.CartDetail", b =>
                {
                    b.HasOne("backend.Models.Client.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Admin.NguyenLieu", "RauCu")
                        .WithMany()
                        .HasForeignKey("RauCuNguyenLieuId");

                    b.Navigation("Cart");

                    b.Navigation("RauCu");
                });

            modelBuilder.Entity("backend.Models.Client.CartDetailTopping", b =>
                {
                    b.HasOne("backend.Models.Client.CartDetail", "CartDetail")
                        .WithMany("Toppings")
                        .HasForeignKey("CartDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Admin.SanPham", "SanPhamTopping")
                        .WithMany()
                        .HasForeignKey("ToppingSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartDetail");

                    b.Navigation("SanPhamTopping");
                });

            modelBuilder.Entity("backend.Models.Client.Order", b =>
                {
                    b.HasOne("backend.Models.Client.TaiKhoanKhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId");

                    b.HasOne("backend.Models.Admin.CuaHang", "CuaHang")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Admin.TaiKhoanNoiBo", "TaiKhoanPOS")
                        .WithMany()
                        .HasForeignKey("TaiKhoanNoiBoId");

                    b.Navigation("CuaHang");

                    b.Navigation("KhachHang");

                    b.Navigation("TaiKhoanPOS");
                });

            modelBuilder.Entity("backend.Models.Client.OrderDetail", b =>
                {
                    b.HasOne("backend.Models.Client.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Admin.NguyenLieu", "RauCu")
                        .WithMany()
                        .HasForeignKey("RauCuNguyenLieuId");

                    b.Navigation("Order");

                    b.Navigation("RauCu");
                });

            modelBuilder.Entity("backend.Models.Client.OrderDetailTopping", b =>
                {
                    b.HasOne("backend.Models.Client.OrderDetail", "OrderDetail")
                        .WithMany("OrderDetailToppings")
                        .HasForeignKey("OrderDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Admin.SanPham", "SanPhamTopping")
                        .WithMany()
                        .HasForeignKey("ToppingSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderDetail");

                    b.Navigation("SanPhamTopping");
                });

            modelBuilder.Entity("backend.Models.Client.TaiKhoanKhachHang", b =>
                {
                    b.HasOne("backend.Models.Admin.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("ChucVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("backend.Models.Admin.ChucVu", b =>
                {
                    b.Navigation("taiKhoanNoiBos");
                });

            modelBuilder.Entity("backend.Models.Admin.TheLoai", b =>
                {
                    b.Navigation("sanPhams");
                });

            modelBuilder.Entity("backend.Models.Client.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("backend.Models.Client.CartDetail", b =>
                {
                    b.Navigation("Toppings");
                });

            modelBuilder.Entity("backend.Models.Client.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("backend.Models.Client.OrderDetail", b =>
                {
                    b.Navigation("OrderDetailToppings");
                });
#pragma warning restore 612, 618
        }
    }
}
